spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9876
jstorage:
  client:
    url: http://localhost:8765/api
jaccount:
  deactivation-time: ${DEACTIVATION_TIME:15m}
  code-length: ${CODE_LENGTH:4}
  activity-time: ${ACTIVITY_TIME:10m}
  offline-after-time: ${OFFLINE_AFTER_TIME:10m}
  service:
    email: ${SERVICE_MAIL_USERNAME}
    host: ${SERVICE_HOST:http://localhost:8765/${spring.application.name}${server.servlet.context-path}}